<a href="https://colab.research.google.com/github/IgorRachev27/Homework/blob/main/hw%20lecture%203%2C4/Part_1_HW_Write_our_own_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [1]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Writing lib.py


In [2]:
from lib import summ

In [3]:
summ(2,6)

8

Попробуем запустить через "терминал"

In [4]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [5]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


Overwriting lib.py


In [6]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [7]:
%%writefile my_math_lib.py

import numpy as np

def deg_to_rad(x):
    return x*np.pi/180  

def rad_to_deg(x):
    return x*180/np.pi

def discriminant(x,y,z): # Дискриминант - подкорневое выражение при решении квадратного уравнения,
                         # т.е это не корни. Пишу это потому что в задании говорится про корни уравнения
    return y**2-4*x*z

def power_base_sum(x,y):
    return sum([int(i) for i in str(x**y)])

def magic_square(n): # метод Делаира
    M=int(n*(n**2+1)/2)

    #построим первый вспомогательный квадрат
    mass=[i for i in range(n)]
    mass.remove((n-1)/2)
    mass.insert(0,int((n-1)/2))
    final=[]
    for i in range(n):
        final.append(mass[-i:]+mass[0:-i])
    dop_kv1=np.array(final)*n
    dop_kv1
    
    # построим второй вспомогательный квадрат
    mass=[i for i in range(n)]
    mass.sort(reverse=True)
    mass.remove((n-1)/2)
    mass.insert(n-1,int((n-1)/2))

    shift = lambda l, n: l[-n:] + l[:-n]
    final=[]
    for i in range(n):
        final.append(shift(mass,-i))
    dop_kv2=np.array(final)+1
    dop_kv2
    
    #вывод квадрата
    mag_kv=dop_kv1+dop_kv2
    print(mag_kv)
    
def mult_list(x): #умножение всех элементов массива
    a=1
    for i in x:
        a=a*i
    print(a)
    
def create_list(n):
    a=[]
    for i in range(1,n+1):
        a.append(i**2)
    print(a)

Writing my_math_lib.py


# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [8]:
from my_math_lib import *

In [9]:
discriminant(0,3,4)

9

In [10]:
magic_square(5)

[[15  4  7 16 23]
 [24 12  1  8 20]
 [17 21 13  5  9]
 [ 6 18 25 14  2]
 [ 3 10 19 22 11]]


# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [11]:
#TODO

In [12]:
%%writefile my_math_lib.py

import numpy as np

def deg_to_rad(x):
    return x*np.pi/180  

def rad_to_deg(x):
    return x*180/np.pi

def discriminant(x,y,z): # Дискриминант - подкорневое выражение при решении квадратного уравнения,
                         # т.е это не корни. Пишу это потому что в задании говорится про корни уравнения
    return y**2-4*x*z

def power_base_sum(x,y):
    return sum([int(i) for i in str(x**y)])

def magic_square(n): # метод Делаира
    M=int(n*(n**2+1)/2)

    #построим первый вспомогательный квадрат
    mass=[i for i in range(n)]
    mass.remove((n-1)/2)
    mass.insert(0,int((n-1)/2))
    final=[]
    for i in range(n):
        final.append(mass[-i:]+mass[0:-i])
    dop_kv1=np.array(final)*n
    dop_kv1
    
    # построим второй вспомогательный квадрат
    mass=[i for i in range(n)]
    mass.sort(reverse=True)
    mass.remove((n-1)/2)
    mass.insert(n-1,int((n-1)/2))

    shift = lambda l, n: l[-n:] + l[:-n]
    final=[]
    for i in range(n):
        final.append(shift(mass,-i))
    dop_kv2=np.array(final)+1
    dop_kv2
    
    #вывод квадрата
    mag_kv=dop_kv1+dop_kv2
    print(mag_kv)
    
def mult_list(x): #умножение всех элементов массива
    a=1
    for i in x:
        a=a*i
    print(a)
    
def create_list(n):
    a=[]
    for i in range(1,n+1):
        a.append(i**2)
    print(a)

    
import sys

x= int( sys.argv[1] )

if __name__ == "__main__":
    print(magic_square(x))

Overwriting my_math_lib.py


In [13]:
# Пример вызова функции - Вы можете вызвать любую другую
!python3 my_math_lib.py 11 # Например если в __main__ вы указали def discriminant()

[[ 66  10  20  30  40  49  70  80  90 100 116]
 [120  64   8  18  27  37  47  68  78  94 110]
 [108 118  62   5  15  25  35  45  72  88  98]
 [ 96 106 115  59   3  13  23  39  55  76  86]
 [ 84  93 103 113  57   1  17  33  43  53  74]
 [ 71  81  91 101 111  61  11  21  31  41  51]
 [ 48  69  79  89 105 121  65   9  19  29  38]
 [ 36  46  67  83  99 109 119  63   7  16  26]
 [ 24  34  50  77  87  97 107 117  60   4  14]
 [ 12  28  44  54  75  85  95 104 114  58   2]
 [  6  22  32  42  52  73  82  92 102 112  56]]
None
