<a href="https://colab.research.google.com/github/IgorRachev27/Homework/blob/main/hw%20lecture%207%20matrices/HW_7_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [ ]:
import numpy as np

# **1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

a='''Основная идея soft similarity заключается в том, что сходство между признаĸами известно из обычных источников типа академического словаря и не нуждается в изучении на основе данных. При отсутствии сходства между признаками, soft similarity равно стандартному сходству. Soft cosine measure по сравнению с обычным косинусом корректирует свои значения на дополнительную матрицу признаков полученных путём математических расчётов. Например, подсчитывается сколько раз то или иное слово появлялось в тексте.
Основная идея различия soft similarity и soft cosine measure заключается в более глубокой проработке признаков модели. Если в случае с  soft similarity берутся обычные признаки из открытых источников, то, в случае с soft cosine measure, новые качества признаков получаются путём проведения математических операций над признаками. 
На мой взгляд основным примером использования в данном случае является модель отвечающая за автоподбор слов при наборе текста на смартфонах или в поисковой строке браузера.'''


In [ ]:
len(list(a.split(' ')))

135

# __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [ ]:
A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])
print('сумма матриц\n',A+B)
print()
print('произведение матриц\n',A@B)

сумма матриц
 [[ 5 -3]
 [ 3  5]]

произведение матриц
 [[  4 -11]
 [ 12  -3]]


# __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [ ]:
A=np.array([[1,7],[3,-6]])
B=np.array([[0,5],[2,-1]])
C=np.array([[2,-4],[1,1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

# __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [ ]:
A=np.array([[4,1],[5,-2],[2,3]])
print(A@A.T)
print()
print(A.T@A)

[[17 18 11]
 [18 29  4]
 [11  4 13]]

[[45  0]
 [ 0 14]]


# 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def mult_matrix(a,b):
    oshibka=0
    glavny=[] # финальный массив с делением на "подмассивы". результат перемножения матриц (наша искомая матрица)
    el1=[] # массив элементов матрицы, идущих сплошняком (до преобразования "массивы в массиве")
    el2=[] # вспомогательный массив, куда попадают первичные элементы перед тем как будет посчитана их сумма

############################################################################################################# 
# проверка того является ли массив матрицей или нет
    proverka_a=len(a[0])
    for i in range(len(a)):
        if proverka_a==len(a[i]):    
            pass
        else:
            print(f'первый массив это не матрица, ошибка в подмассиве №{i+1} или 1')
            oshibka=1
    proverka_b=len(b[0])
    for g in range(len(b)):
        if proverka_b==len(b[g]):
            pass
        else:
            print(f'второй массив это не матрица, ошибка в подмассиве №{g+1} или 1')
            oshibka=1
#############################################################################################################        
            
            
            
    if oshibka!=1:
        if len(a[0])==len(b):  # проверка равенства числа столбцов первой матрицы числу строк второй

            for l in range(len(a)):
                for f in range(len(b[0])):    
                    for i in range(len(a[0])):  
                        k=a[l][i]*b[i][f]
                        el2.append(k)
                    el1.append(sum(el2))
                    el2.clear()
        
        else:
            print('число столбцов в первой матрице не равно числу строк во второй')
            oshibka=2
                    

    if oshibka!=1 and oshibka!=2:
        for i in range(len(a)):
            glavny.append(el1[0:len(b[0])])
            del el1[0:len(b[0])]
        print(glavny)

In [ ]:
# ячейка для проверки
a=[[1,2,3,4],[4,5,6,4],[9,1,3,4]]
b=[[7,8,9,10],[10,11,12,15],[13,14,15,12],[1,1,1,18]]

c=np.array(a)   
d=np.array(b)    
try:
    print(c.dot(b))  
except:
    print('матрицы не удовлетворяют основному требованию')


[[ 70  76  82 148]
 [160 175 190 259]
 [116 129 142 213]]


In [ ]:
mult_matrix(a,b)

[[70, 76, 82, 148], [160, 175, 190, 259], [116, 129, 142, 213]]


# __6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$



In [ ]:
x=123
A=np.array([[np.sin(x), -np.cos(x)],[np.cos(x),np.sin(x)]])
print('определитель матрицы А =',np.linalg.det(A))
print()
B=np.array([[8,4,6],[0,5,1],[0,0,9]])
print('определитель матрицы В =',int(np.linalg.det(B)))
print()
C=np.array([[2,3,4],[5,6,7],[8,9,10]])
print('определитель матрицы C =',int(np.linalg.det(C)))

определитель матрицы А = 1.0

определитель матрицы В = 360

определитель матрицы C = 0


# __7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

для доказательства правильности расчётов придумаем матрицу с определителем равным 4 и посчитаем определители
других матриц

In [ ]:
A=np.array([[0,1,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
print('определитель матрицы А =',np.linalg.det(A))
A2=A@A
print('определитель матрицы А^2 =',np.linalg.det(A2))
print('определитель матрицы А.T =',np.linalg.det(A.T))
a=2*A
print('определитель матрицы 2*А =',np.linalg.det(a))

определитель матрицы А = 3.999999999999999
определитель матрицы А^2 = 15.999999999999977
определитель матрицы А.T = 4.0
определитель матрицы 2*А = 63.99999999999998


# __8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [ ]:
A=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
print('определитель матрицы А =',np.linalg.det(A), "значит матрица вырожденная")

определитель матрицы А = 0.0 значит матрица вырожденная


# __9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [ ]:
A=np.array([[1,2,3],[1,1,1],[2,3,4]])
print(f'ранг матрицы А = {np.linalg.matrix_rank(A)}')
print()
B=np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
print(f'ранг матрицы B = {np.linalg.matrix_rank(B)}')

ранг матрицы А = 2

ранг матрицы B = 3


# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)